name: dental-content-schedule
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/smile-sync-schedule  
    branch: main
  build_command: npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
